config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root :to => 'static_pages#home'
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/user/:id' => 'users#show', :as => :user
  get '/user/:id/edit' => 'users#edit', :as => :edit_user
  patch 'user/:id' => 'users#update'
  resource 'users'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/properties' => 'properties#index'
  get '/property/new' => 'properties#new'
  get '/property/:id' => 'properties#show', :as => :property
  get '/property/:id/edit' => 'properties#edit', :as => :edit_property
  patch 'property/:id' => 'properties#update'
  resource 'properties'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  def self.search(search)
    where("street ILIKE ? OR suburbs ILIKE ? OR postcode ILIKE ? OR region ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  validates :house_no, presence: true

  validates :street, presence: true

  validates :suburbs, presence: true

  validates :postcode, presence: true,
            length: {minimum: 4, maximum: 4}

  validates :region, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true,
            length: {maximum: 20}

  validates :last_name, presence: true,
            length: {maximum: 20}

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
            length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  validates :password, presence: true,
            length: {minimum: 6, maximum: 20}

  validates :contact_number, presence: true,
           length: {minimum: 10, maximum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController


  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
    if params[:search]
      @properties = Property.search(params[:search]).order("created_at DESC")
    else
      @properties = Property.all.order("created_at DESC")
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.fetch(:property, {})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.password == (params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash[:danger] = 'Invalid email/password combination!'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "Welcome to the David's Rental!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :contact_number, :user_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small style="font-size: 16px">
    David's Rental <i class="fa fa-copyright"></i>
  </small>
  <nav>
    <ul>
      <li>Contact Us:</li>
      <li style="font-size: 16px">
        <%= link_to '#' do %>
            <i class="fa fa-facebook-square"></i>
        <% end %>
      </li>
      <li>
        <%= link_to '#' do %>
            <i class="fa fa-whatsapp"></i>
        <% end %>
      </li>
      <li>
        <%= link_to '#', class: 'hidden' do %>
            <i class="fa fa-facebook-official"></i>
        <% end %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <%= link_to root_path, id: 'logo' do %>
        <i class="fa fa-home"></i> David's Rental
    <% end %>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to logout_path, method: :delete do %>
                      Log out <i class="fa fa-sign-out"></i>
                  <% end %>
                </li>
              </ul>
            </li>
        <% else %>
            <li>
              <%= link_to login_path do %>
                  Log in<span style="margin-left: 10px"></span><i class="fa fa-sign-in"></i>
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Untitled</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body>
<%= render 'layouts/header' %>
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/properties/_form.html.erb
<%= form_for(property) do |f| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<body>
<div class="container">
  <h1 class="text-center" style="font-weight: bold">Update Property</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@property) do |f| %>

          <%= f.label :house_no do %>
              <i class="fa fa-home"></i><span style="padding-right: 1em"></span>House Number
          <% end %>
          <%= f.text_field :house_no, class: 'form-control', placeholder: "Eg: Unit 1/24 or 24" %>
          <h6 style="color: #666666; font-style: italic">Please key in unit number here as well
            (if you have any)</h6>

          <%= f.label :street do %>
              <i class="fa fa-road"></i><span style="padding-right: 1em"></span>Street
          <% end %>
          <%= f.text_field :street, class: 'form-control', placeholder: "Eg: Herston Road" %>

          <%= f.label :suburbs do %>
              <i class="fa fa-map-signs"></i><span style="padding-right: 1em"></span>Suburbs
          <% end %>
          <%= f.text_field :suburbs, class: 'form-control', placeholder: "Eg, Kelvin Grove" %>

          <%= f.label :postcode do %>
              <i class="fa fa-map-pin"></i><span style="padding-right: 1em"></span>Postcode
          <% end %>
          <%= f.text_field :postcode, class: 'form-control', placeholder: "Eg: 4059" %>

          <%= f.label :region do %>
              <i class="fa fa-globe"></i><span style="padding-right: 1em"></span>Region
          <% end %>
          <%= f.text_field :region, class: 'form-control', placeholder: "Eg: QLD" %>

          <%= f.label :price do %>
              <i class="fa fa-dollar"></i><span style="padding-right: 1em"></span>Price
          <% end %>
          <%= f.number_field :price, class: 'form-control', placeholder: "Eg: 520" %>

          <%= f.label :bedroom_no do %>
              <i class="fa fa-bed"></i><span style="padding-right: 1em"></span>Bedroom Number
          <% end %>
          <%= f.number_field :bedroom_no, class: 'form-control', placeholder: "Eg: 2" %>

          <%= f.label :bathroom_no do %>
              <i class="fa fa-bath"></i><span style="padding-right: 1em"></span>Bathroom Number
          <% end %>
          <%= f.number_field :bathroom_no, class: 'form-control', placeholder: "Eg: 2" %>

          <%= f.label :garage_no do %>
              <i class="fa fa-car"></i><span style="padding-right: 1em"></span>Garage Number
          <% end %>
          <%= f.number_field :garage_no, class: 'form-control', placeholder: "Eg: 2" %>

          <%= f.label :picture_path do %>
              <i class="fa fa-image"></i><span style="padding-right: 1em"></span>Please upload one image to represent your property
          <% end %>
          <%= f.file_field :picture_path, class: 'form-control' %>

          <div>
            <%= f.submit "Save Changes", class: "btn btn-primary btn-block" %>
          </div>
      <% end %>
    </div>
  </div>
</div>
</body>

app/views/properties/index.html.erb
<body>
<table>
  <tbody>
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 text-center input-group">
        <%= form_tag(properties_path, :method => 'get') do %>
            <%= text_field_tag :search, params[:search], class: 'form-control', value: '',
                               placeholder: "Search Properties (Eg: Tait Street or Kelvin Grove or 4059 or QLD)" %>
            <span class="input-group-btn">
              <%= button_tag(type: 'submit', class: 'btn btn-primary', :name => nil) do %>
                Search <i class="fa fa-search"></i>
              <% end %>
            </span>
        <% end %>
      </div>
    </div>
    <br>
    <% if @properties.blank? %>
        <div class="alert alert-danger text-center">
          <h4>There is no property containing the term <%= params[:search] %>.</h4>
        </div>
    <% end %>
    <div class="row">
      <% @properties.each do |property| %>
          <div class="col-md-4 text-center">
            <%= link_to property do %>
                <%= image_tag(property.picture_path, size: '300x180', alt: 'View') %>
            <% end %>
            <h4>
              <%= property.house_no + ", " + property.street + ", " + property.suburbs + ", " + property.postcode + " " + property.region %>
            </h4>
            <h4><i class="fa fa-dollar"></i> <%= property.price.to_s + " per week" %></h4>
            <%= link_to property, class: 'btn btn-default btn-block' do %>
                <h4><i class="fa fa-search-plus"></i> More Details</h4>
            <% end %>
            <br>
          </div>
      <% end %>
    </div>
  </div>
  </tbody>
</table>
</body>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>
<body>
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 text-center">
    <%= image_tag @property.picture_path %>
  </div>
  <div class="col-lg-6 col-lg-offset-3 text-center">
    <h3><%= @property.house_no + ", " + @property.street + ", " + @property.suburbs + ", " + @property.postcode + " " + @property.region %></h3>
    <h3>
      <i class="fa fa-bed"></i> <%= @property.bedroom_no %>
      <span style="margin-left: 1em"></span>
      <i class="fa fa-bath"></i> <%= @property.bathroom_no %>
      <span style="margin-left: 1em"></span>
      <i class="fa fa-car"></i> <%= @property.garage_no %>
    </h3>
    <h3><i class="fa fa-dollar"></i> <%= @property.price.to_s + " per week" %></h3>
  </div>
</div>
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 text-center">
    <%= link_to '#', class: 'btn btn-success' do %>
        <h4><i class="fa fa-calendar-check-o"></i><span style="padding-right: 10px"></span>Book Inspection</h4>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 text-center">
    <%= link_to request.referer.present? ? request.referer : properties_path, class: 'btn btn-positive' do %>
        <h5><u>Back</u></h5>
    <% end %>
  </div>
</div>
</body>

app/views/shared/_error_messages_html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/help.html.erb
<body>
  <div style="margin-left: 10px">
    <h1>Guidelines</h1>
  </div>
</body>

app/views/static_pages/home.html.erb
<body>
<% if logged_in? && current_user.user_type == 'customer' %>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="center item active">
          <h1>Good day <%= current_user.first_name %>!</h1>
          <h2>Check out the best rates properties we have now!</h2>
          <%= link_to "View Properties", properties_path, class: 'btn btn-lg btn-success' %>
        </div>
        <div class="item">
          <h1 class="text-center">Hey!</h1>
          <h2 class="text-center">Customer page</h2>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
<% end %>
<% if logged_in? && current_user.user_type == 'property_owner' %>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="center item active">
          <h1>Good day <%= current_user.first_name %>!</h1>
          <h2>Upload your property image and details now!</h2>
        </div>
        <div class="item">
          <h1 class="text-center">Hey!</h1>
          <h2 class="text-center">Property Owner page</h2>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
<% end %>
<% if logged_in? && current_user.user_type == 'owner' %>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="center item active">
          <h1>Welcome back <%= current_user.first_name %>!</h1>
          <h2>There are 3 insepctions waiting you to allocate.</h2>
          <%= link_to "Allocate Inspection", '#', class: 'btn btn-lg btn-default' %>
        </div>
        <div class="center item">
          <h1 class="text-center">Manage Properties</h1>
          <h2 class="text-center"><i class="fa fa-home"></i></h2>
          <div class="btn-group">
            <%= link_to "Add Property", new_properties_path, class: 'btn btn-lg btn-primary' %>
            <%= link_to "Update Property", '#', class: 'btn btn-lg btn-primary' %>
            <%= link_to "Remove Property", '#', class: 'btn btn-lg btn-primary' %>
          </div>

        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-md-6" style='border:1.5px black solid;'>
          <h2 class="text-center">Report</h2>
          <h3><%= "Total properties available -------------------------------- " + Property.all.count.to_s %></h3>
        </div>
      </div>
    </div>
<% end %>
<% if logged_in? && current_user.user_type == 'employee' %>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="center item active">
          <h1>Good day <%= current_user.first_name %>!</h1>
          <h2>Check your inspection assignments</h2>
          <%= link_to "Check Assignments", '#', class: 'btn btn-lg btn-default' %>
        </div>
        <div class="item">
          <h1 class="text-center">Hey!</h1>
          <h2 class="text-center">Employee page</h2>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
<% end %>
<% if !logged_in? %>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
        <li data-target="#carousel-example-generic" data-slide-to="4"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="center item active">
          <h1>Welcome to the David's Rental</h1>

          <h2>
            Check out the best rates properties we have now!
          </h2>

          <%= link_to "Sign up now!", new_users_path, class: 'btn btn-lg btn-primary' %>
        </div>
        <div class="item">
          <p class="text-center"><%= image_tag '/properties/1.jpg' %></p>
        </div>
        <div class="item">
          <p class="text-center"><%= image_tag '/properties/5.jpg' %></p>
        </div>
        <div class="item">
          <p class="text-center"><%= image_tag '/properties/8.jpg' %></p>
        </div>
        <div class="item">
          <p class="text-center"><%= image_tag '/properties/13.jpg' %></p>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
<% end %>
</body>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <% if current_user.user_type == 'customer' %>
          <%= image_tag('/profile-image/customer.png', style: 'height:70%;' 'width:70%;') %>
          <h4>
            <%= link_to edit_user_path(current_user) do %>
                <span style="padding-right: 4em"></span><i class="fa fa-pencil-square"></i> Edit Profile
            <% end %>
          </h4>
      <% end %>
      <% if current_user.user_type == 'property_owner' %>
          <%= image_tag('/profile-image/Owner.png', style: 'height:70%;' 'width:70%;') %>
          <h4>
            <%= link_to edit_user_path(current_user) do %>
                <span style="padding-right: 4em"></span><i class="fa fa-pencil-square"></i> Edit Profile
            <% end %>
          </h4>
      <% end %>
      <% if current_user.user_type == 'owner' %>
          <%= image_tag('/profile-image/gary.png', style: 'height:70%;' 'width:70%;') %>
          <h4>
            <%= link_to edit_user_path(current_user) do %>
                <span style="padding-right: 4em"></span><i class="fa fa-pencil-square"></i> Edit Profile
            <% end %>
          </h4>
      <% end %>
      <% if current_user.user_type == 'employee' %>
          <%= image_tag('/profile-image/employee.png', style: 'height:70%;' 'width:70%;') %>
          <h4>
            <%= link_to edit_user_path(current_user) do %>
                <span style="padding-right: 4em"></span><i class="fa fa-pencil-square"></i> Edit Profile
            <% end %>
          </h4>
      <% end %>
    </div>
    <div class="col-md-4">
      <h2>
        <i class="fa fa-user-circle"></i><span style="padding-right: 2em"></span><%= current_user.first_name + " " + current_user.last_name %>
      </h2>
      <h3><i class="fa fa-envelope fa-lg"></i><span style="padding-right: 2.5em"></span><%= current_user.email %></h3>
      <h3>
        &nbsp;<i class="fa fa-phone fa-lg"></i><span style="padding-right: 2.5em"></span><%= current_user.contact_number %>
      </h3>
      <% if current_user.user_type == 'customer' %>
          <h3>
            <i class="fa fa-id-card fa-lg"></i><span style="padding-right: 2.3em"></span>Customer
          </h3>
      <% end %>
      <% if current_user.user_type == 'property_owner' %>
          <h3>
            <i class="fa fa-id-card fa-lg"></i><span style="padding-right: 2.3em"></span>Property Owner
          </h3>
      <% end %>
      <% if current_user.user_type == 'employee' %>
          <h3>
            <i class="fa fa-id-card fa-lg"></i><span style="padding-right: 2.3em"></span>Employee
          </h3>
      <% end %>
      <% if current_user.user_type == 'owner' %>
          <h3>
            <i class="fa fa-id-card fa-lg"></i><span style="padding-right: 2.3em"></span>Owner
          </h3>
      <% end %>
    </div>
  </div>
</div>

</body>